---
title: "nbastatR"
author: "Abisai Lujan"
date: "2025-02-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,eval=FALSE}
devtools::install_github("abresler/nbastatR", force=T)
```


```{r}
library(nbastatR)
library(tidyverse)

Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)
```

You dont know how the outside teams' names are spelled or abbreviated 
```{r}
#Get NBA Teams aka names of the teams 
TEAM=nba_teams(league="NBA") %>% 
  filter(yearPlayedLast==2024,idLeague==2) %>%
  select(nameTeam,idTeam,slugTeam)
```

goes online and Pulls all the data in games the 2024-2025 season. Provides ids for each game 
```{r}
#Game Data for 2023/5? 
GAME2025=game_logs(
  seasons = 2025,
  league = "NBA",
  result_types = "team",
  season_types = "Regular Season",
  nest_data = F,
  assign_to_environment = TRUE,
  return_message = TRUE
)
```


```{r}
#Selecting One Game to Illustrate Cleaning
GAME=filter(GAME2025,idGame==22400062) %>%
              select(idGame,nameTeam,locationGame,orebTeam,ptsTeam)
```


```{r}
#Split Data Up Into Home and Away
HOME=GAME %>% filter(locationGame=="H") %>% select(-locationGame)
AWAY=GAME %>% filter(locationGame=="A") %>% select(-locationGame)
```


Rename to allow for merging
```{r}
#Rename Variables
HOME2 = HOME %>% rename(Home=nameTeam,OREB_H=orebTeam,PTS_H=ptsTeam)
AWAY2 = AWAY %>% rename(Away=nameTeam,OREB_A=orebTeam,PTS_A=ptsTeam)
```


```{r}
#Merge Datasets and Create Spread, Total, and OREB

COMBINED = full_join(HOME2,AWAY2, by=c("idGame")) %>%
            mutate(Spread=PTS_H-PTS_A,
                   Total=PTS_H+PTS_A,
                   OREB=OREB_H+OREB_A) %>%
            select(idGame,Away,Home,Spread,Total,OREB,everything())
```


```{r}
#Box Score Data for Individual Game
BOX2025=unnest(box_scores(game_ids=c(22400062),
                      box_score_types="Advanced",
                      result_types="team"
))
```

